import sampleOotdPhoto from '@/shared/assets/ootd/sample-ootd-1.png';
import type { ClosetItem, OotdPost } from './types';

export const mockClosetItems: ClosetItem[] = [
  {
    id: 'closet-1',
    brand: 'A.P.C',
    name: 'Petit New Standard',
    category: '팬츠',
    imageUrl: 'https://picsum.photos/seed/closet-1/80/80',
    lastWornDaysAgo: 14,
    verifiedCount: 2,
  },
  {
    id: 'closet-2',
    brand: 'Resolute',
    name: '710 pants',
    category: '데님',
    imageUrl: 'https://picsum.photos/seed/closet-2/80/80',
    lastWornDaysAgo: 7,
    verifiedCount: 2,
  },
  {
    id: 'closet-3',
    brand: 'Levis',
    name: 'LVC 1955 501',
    category: '데님',
    imageUrl: 'https://picsum.photos/seed/closet-3/80/80',
    lastWornDaysAgo: 3,
    verifiedCount: 1,
  },
  {
    id: 'closet-4',
    brand: 'Guidi',
    name: '788z Boots',
    category: '부츠',
    imageUrl: 'https://picsum.photos/seed/closet-4/80/80',
    lastWornDaysAgo: 20,
    verifiedCount: 4,
  },
  {
    id: 'closet-5',
    brand: 'Adidas',
    name: 'Adicolor Classics Firebird Track Suit',
    category: '트랙수트',
    imageUrl: 'https://picsum.photos/seed/closet-5/80/80',
    lastWornDaysAgo: 4,
    verifiedCount: 2,
  },
  {
    id: 'closet-6',
    brand: 'Nike',
    name: "Air Force 1 '07",
    category: '스니커즈',
    imageUrl: 'https://picsum.photos/seed/closet-6/80/80',
    lastWornDaysAgo: 7,
    verifiedCount: 3,
  },
];

export const mockOotdPost: OotdPost = {
  id: 'ootd-1',
  imageUrl: sampleOotdPhoto,
  author: { id: 'user-sujin', name: 'Sujin', followerCount: 101, feedCount: 60 },
  likeCount: 1234,
  bookmarkCount: 1234,
  liked: false,
  bookmarked: false,
  isOwner: true,
  isFollowing: true,
  isBlocked: false,
  taggedItems: [
    {
      id: 'tag-1',
      brand: 'A.P.C',
      name: 'Petit New Standard',
      category: '팬츠',
      status: '미판매',
      canOffer: false,
      position: { x: 60, y: 8 },
      closetItemId: 'closet-1',
    },
    {
      id: 'tag-2',
      brand: 'Levis',
      name: 'LVC 1955 501',
      category: '데님',
      status: '미판매',
      canOffer: true,
      position: { x: 55, y: 30 },
      closetItemId: 'closet-3',
    },
    {
      id: 'tag-3',
      brand: 'Resolute',
      name: '710 Denim',
      category: '데님',
      status: '판매중',
      price: 250000,
      position: { x: 45, y: 60 },
      closetItemId: 'closet-2',
    },
    {
      id: 'tag-4',
      brand: 'Guidi',
      name: '788z Boots',
      category: '부츠',
      status: '판매중',
      price: 900000,
      position: { x: 40, y: 90 },
      closetItemId: 'closet-4',
    },
  ],
};
