import sampleOotdPhoto from '@/shared/assets/ootd/sample-ootd-1.png';
import type { ClosetItem, OotdPost } from './types';

export const mockClosetItems: ClosetItem[] = [
  {
    id: 1,
    brand: 'A.P.C',
    name: 'Petit New Standard',
    imageUrl: 'https://picsum.photos/seed/closet-1/80/80',
    lastWornDaysAgo: 14,
    verifiedCount: 2,
    purchaseOfferEnabled: false,
  },
  {
    id: 2,
    brand: 'Resolute',
    name: '710 pants',
    imageUrl: 'https://picsum.photos/seed/closet-2/80/80',
    lastWornDaysAgo: 7,
    verifiedCount: 2,
    purchaseOfferEnabled: true,
  },
  {
    id: 3,
    brand: 'Levis',
    name: 'LVC 1955 501',
    imageUrl: 'https://picsum.photos/seed/closet-3/80/80',
    lastWornDaysAgo: 3,
    verifiedCount: 1,
    purchaseOfferEnabled: true,
  },
  {
    id: 4,
    brand: 'Guidi',
    name: '788z Boots',
    imageUrl: 'https://picsum.photos/seed/closet-4/80/80',
    lastWornDaysAgo: 20,
    verifiedCount: 4,
    purchaseOfferEnabled: false,
  },
  {
    id: 5,
    brand: 'Adidas',
    name: 'Adicolor Classics Firebird Track Suit',
    imageUrl: 'https://picsum.photos/seed/closet-5/80/80',
    lastWornDaysAgo: 4,
    verifiedCount: 2,
    purchaseOfferEnabled: false,
  },
  {
    id: 6,
    brand: 'Nike',
    name: "Air Force 1 '07",
    imageUrl: 'https://picsum.photos/seed/closet-6/80/80',
    lastWornDaysAgo: 7,
    verifiedCount: 3,
    purchaseOfferEnabled: true,
  },
];

export const mockOotdPost: OotdPost = {
  id: 1,
  imageUrl: sampleOotdPhoto,
  author: { id: 1, name: 'Sujin', avatarUrl: null, followerCount: 101, feedCount: 60 },
  likeCount: 1234,
  bookmarkCount: 1234,
  liked: false,
  bookmarked: false,
  isOwner: true,
  isFollowing: true,
  taggedItems: [
    {
      id: 1,
      itemId: 1,
      brand: 'A.P.C',
      name: 'Petit New Standard',
      category: '팬츠',
      status: '미판매_제안불가',
      wished: false,
      position: { x: 60, y: 8 },
      bbox: { x: 0.52, y: 0.02, width: 0.16, height: 0.12 },
    },
    {
      id: 2,
      itemId: 3,
      brand: 'Levis',
      name: 'LVC 1955 501',
      category: '데님',
      status: '미판매_제안가능',
      wished: false,
      position: { x: 55, y: 30 },
      bbox: { x: 0.47, y: 0.24, width: 0.16, height: 0.12 },
    },
    {
      id: 3,
      itemId: 2,
      brand: 'Resolute',
      name: '710 Denim',
      category: '데님',
      status: '판매중',
      price: 250000,
      wished: false,
      position: { x: 45, y: 60 },
      bbox: { x: 0.37, y: 0.54, width: 0.16, height: 0.12 },
    },
    {
      id: 4,
      itemId: 4,
      brand: 'Guidi',
      name: '788z Boots',
      category: '부츠',
      status: '판매중',
      price: 900000,
      wished: false,
      position: { x: 40, y: 90 },
      bbox: { x: 0.32, y: 0.84, width: 0.16, height: 0.12 },
    },
  ],
};
